# Generated by Django 3.1.4 on 2020-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=110, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='marka',
            name='image',
            field=models.ImageField(blank=True, upload_to='marka_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='image',
            field=models.ImageField(blank=True, upload_to='sport_images', verbose_name='Image'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug',)},
        ),
    ]
