# Generated by Django 3.1.4 on 2020-12-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201223_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='product.Tag'),
        ),
    ]
