# Generated by Django 3.1.4 on 2020-12-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
