# Generated by Django 3.1.4 on 2020-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201223_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_second',
            field=models.BooleanField(default=False, verbose_name='is_second'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_third',
            field=models.BooleanField(default=False, verbose_name='is_third'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='is_main'),
        ),
    ]
