# Generated by Django 3.1.4 on 2021-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201223_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Name'),
        ),
    ]
