# Generated by Django 3.1.4 on 2020-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone_num', models.CharField(max_length=50, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact_Message',
                'verbose_name_plural': 'Contact_Messages',
                'db_table': 'contact_message',
                'ordering': ('-created_at',),
            },
        ),
    ]
